### ISSUE TITLE
Limits index out of range

### ISSUE THREAD

**Issue by Gonzalo933** [bholagabbar/capsnap#1]
Hello,
I'm trying to run it and it seems to fail after calling the function `find_black_bar_and_draw_lines_on_black_image`.

This is the error (after debug, it seems that limits has only one element): 
> Traceback (most recent call last):
>   File "capsnap.py", line 98, in <module>
>     black_bar = img[limits[0]:limits[1], 0:width]
> IndexError: list index out of range

**Comment by bholagabbar** [comment]
That's weird. It works fine for me on the test image (see the refreshing images, the images with processing thumbnails are the results generated). Also, I pulled a fresh copy of this repository and ran the command.
![image](https://cloud.githubusercontent.com/assets/11693595/25629953/fe4b3c92-2f88-11e7-9d16-e8d4d5ba4c23.png)

**Comment by Gonzalo933** [comment]
I will debug it more deeply soon, I run it over windows 7 with Python 3, I will try python 3 on Ubuntu to see if I get the same problem

**Comment by bholagabbar** [comment]
FWIW this is meant to run with python 2.7

**Comment by dsquaredduffy** [comment]
I'm getting the same issue, with the same exact error message. This is on windows 8.1 using python 2.7.

**Comment by Gonzalo933** [comment]
Same error on Python 2.7 on Ubuntu:

> gonzalo@gonzalo-Ubuntu:~/capsnap$ python2 capsnap.py --img IMG-20170114-WA0002.jpg 
> Traceback (most recent call last):
>   File "capsnap.py", line 97, in <module>
>     black_bar = img[limits[0]:limits[1], 0:width]
> IndexError: list index out of range

**Comment by bholagabbar** [comment]
I see. So if you guys are able to find the reason and fix it, I could merge in the pull request :)

**Comment by vicc** [comment]
@bholagabbar  Any updates? Currently on Sierra 10.12.4 running Python 2.7

**Comment by bholagabbar** [comment]
You're free to debug the code if it doesn't work on your system and submit
a patch! I'm not actively working on this project so I don't think any
updates are to be expected :P

**Comment by Gonzalo933** [comment]
Hey, I have made a pull request with a fix, it works on a lot of examples and it's also Python 3 compatible, I have made some test and it seems that when the image have a lot of black in the background the program is unable to find the black bar, but the rest of images should be okay.

I haven't tested on Python 2 but it should work.

I also installed opencv with this command: 
`pip install opencv-python`

Maybe you should add it to the readme (or create a requirements.txt file)

**Comment by bholagabbar** [comment]
@Gonzalo933 Thanks for the PR mate! I'll test it and get back to you on the same.

**Comment by Gonzalo933** [comment]
Did you have time to check if everything was OK with the PR?

**Comment by bholagabbar** [comment]
Yes. Merged in #2
